### ISSUE TITLE
Could you provide video clips of the trained robots on Github or YouTube?

### ISSUE THREAD

**Issue by zhangchuheng123** [cselab/smarties#1]
RACER's results on Mujoco control tasks are awesome, especially for those hardest tasks such as Humanoid/HumanoidStandup/Ant/HalfCheetah. Since no one achieves such high scores (as far as I know) and the performance on previous high score seems saturated on some tasks (e.g. Ant/HalfCheetah), I'm quite curious about what does the performance of these robots after training look like. I believe more people are curious about it too. Could you provide video clips of the trained robots on Github or YouTube? That must attract more people's attention.

**Comment by novatig** [comment]
Sorry for the extremely long wait. I never noticed the issue.

I updated the README with some examples.
From the MuJoCo cases I put Humanoid-v2 because I still had a restart file and it looked good.
My Ant/HalfCheetah policies look similar to those obtained by other libraries/algorithms, I will not add them for now.
When I find the time, I will train a new policy for HumanoidStandup and add it.
